---
# tasks file for haproxy
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: install haproxy config
  template: 
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  vars:
    servers: {{ servers }}

- name: start and enable haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes